- name: Check behat env.
  stat:
    path: "{{ app_directory }}/.env.behat"
  register: run_behat

- name: Check behat features.
  stat:
    path: "{{ app_directory }}/features/pipeline"
  register: behat_features

- name: Run behat tests.
  block:
    - name: Run Behat pipeline tests.
      shell: 'vendor/bin/behat features/pipeline'
      args:
        chdir: "{{ app_directory }}"
  when: run_behat.stat.exists and behat_features.stat.exists
