- name: Print Craft CMS framework version
  debug:
    var: fact_craftcms_version
    verbosity: 1

- name: Check for outdated Craft CMS framework
  debug:
    msg: Craft CMS version ({{ fact_craftcms_version }}) is too old to deploy. Please update framework to v{{ minimum_craftcms_version }} or request a Platform override.
    verbosity: 0
  when: fact_craftcms_version | regex_search('\d+[.]?\d*[.]?\d*') is not version(minimum_craftcms_version, '>=', strict=true)

- include_tasks: platform-override.yml
  when: fact_craftcms_version | regex_search('\d+[.]?\d*[.]?\d*') is not version(minimum_craftcms_version, '>=', strict=true)

- name: Check for codeception.yaml
  stat:
    path: "{{ app_directory }}/codeception.yaml"
  register: codeception_conf
  failed_when: not codeception_conf.stat.exists

- name: Check for testing .env
  stat:
    path: "{{ app_directory }}/tests/.env"
  register: codeception_env
  failed_when: not codeception_env.stat.exists

- name: Install mysql-client
  apt:
    name: mysql-client
    state: present
    install_recommends: no
