- name: Set PHP fpm ini variables
  ini_file:
    path: "/etc/php/{{php_version}}/fpm/php.ini"
    section: PHP
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ php_ini_values }}"
  when: php_ini_values | length > 0

- name: Restart PHP-FPM
  service:
    name: "php{{php_version}}-fpm"
    state: restarted